test.name: Phil
sample.name: Andy
spring.ssl.bundle.pem:
  mybundle:
    keystore:
      certificate: "file:/home/moe/tmp/certs/1/*.crt"
      private-key: "file:/home/moe/tmp/certs/2/*.key"
    truststore:
      certificate: "/home/moe/tmp/certs/3/2.crt"
      private-key: "/home/moe/tmp/certs/4/2.key"
